# Generated by Django 4.2.4 on 2023-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='image_url',
            field=models.URLField(default='default_image_url', max_length=1200),
        ),
        migrations.AlterField(
            model_name='titles',
            name='main_title',
            field=models.CharField(max_length=20),
        ),
    ]
