# Generated by Django 4.2.4 on 2023-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_titles_image_url_alter_titles_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='image_url',
            field=models.CharField(default='default_image_url', max_length=1200),
        ),
    ]
