# Generated by Django 4.2.4 on 2023-09-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='desc',
            new_name='news_desc',
        ),
    ]
