# Generated by Django 4.2.4 on 2023-09-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0002_rename_desc_news_news_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_title',
        ),
    ]
