# Generated by Django 4.2.4 on 2023-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('urdu', models.IntegerField()),
                ('biy', models.IntegerField()),
                ('phy', models.IntegerField()),
                ('chy', models.IntegerField()),
                ('ist', models.IntegerField()),
                ('ps', models.IntegerField()),
                ('total_numbers', models.CharField(max_length=25)),
                ('percentage', models.CharField(max_length=25)),
                ('division', models.CharField(max_length=25)),
            ],
        ),
    ]
